data:
  graphs_path: 'C:\mva_first_semester\ALTEGRAD\molecular-graph-captioning\data\graphs'
  max_description_length: 512

train_contrastive:
  batch_size: 64
  graph_hidden_dim: 256
  graph_out_dim: 512
  adapter_hidden_dim: 768
  llama_hidden_dim: 768
  lr: 1e-4
  temperature: 0.3
  accum_steps: 8

train_instruct:
  dummy: 0

eval:
  batch_size: 64